"""RC101 test collection policy.

Legacy V1/RC contract tests that import modules removed from the shipped V2 runtime
are deliberately excluded from the active regression suite. The classification is
explicit and documented in tests/legacy_contracts/README.md. New V2 tests must not
be added here.
"""

collect_ignore = [
    "test_rc33_policy.py",
    "test_rc35_source_compat.py",
    "test_rc36_media_human.py",
    "test_rc37_editorial.py",
    "test_rc38_editorial.py",
    "test_rc39_editorial_bridge.py",
    "test_rc40_pipeline.py",
    "test_rc41_editorial_mix.py",
    "test_rc42_channel_editorial_weights.py",
    "test_rc43_ui_layout.py",
    "test_rc44_direct_feed_transport.py",
    "test_rc45_cross_language_fact_guard.py",
    "test_rc45_editorial_direction.py",
    "test_rc45_editorial_fit.py",
    "test_rc46_editorial_throughput.py",
    "test_rc47_editorial_quality.py",
    "test_rc48_editorial_learning.py",
    "test_rc49_policy.py",
    "test_rc49_router.py",
    "test_rc51_reaction_feedback.py",
    "test_rc52_dual_reaction_learning.py",
    "test_rc53_production_hardening.py",
    "test_rc54_mtproto_hotfix.py",
    "test_rc55_repeat_refresh.py",
    "test_rc56_reaction_runtime.py",
    "test_rc57_admin_audience_feedback.py",
    "test_rc58_editorial_rebuild.py",
    "test_rc59_universal_policy.py",
    "test_rc60_editorial_quality.py",
    "test_rc61_runtime_fix.py",
    "test_rc62_editorial_control.py",
    "test_rc63_training_mode.py",
    "test_rc64_live_tuning.py",
    "test_rc65_universal_final_editor.py",
    "test_rc66_editorial_queue.py",
    "test_rc67_nonblocking_runtime.py",
    "test_rc68_editorial_value.py",
    "test_rc69_media_language.py",
    "test_rc70_mixed_language.py",
    "test_rc71_editorial_pipeline.py",
    "test_rc72_channel_policy.py",
    "test_rc73_channel_weights.py",
    "test_rc74_universal_runtime.py",
    "test_rc75_channel_settings_ui.py",
    "test_rc76_editorial_weights_persistence.py",
    "test_rc79_runtime.py",
    "test_rc80_dedupe_guard.py",
    "test_rc81_resilience.py",
    "test_rc82_stable_night.py",
]
